services:

  front_end:
    build:  ./frontend/
    container_name: frontend
    restart: always
    ports:
      - 80:80
    depends_on:
      - flask_app

  flask_app:
    build: ./backend/
    container_name: flask_app
    secrets:
      - app_api_key
    ports:
      - "5100:5100"
    depends_on:
      mysql_db:
        condition: service_healthy

  mysql_db:
    build: ./db/
    container_name: mysql_db
    restart: always
    ports:
      - "3306:3306"
    expose:
      - "3306"

  prometheus:
    image: prom/prometheus:v2.51.2
#    container_name: prometheus
    ports:
      - "9091:9090"
    restart: always
    volumes:
      - ./monitoring/promethues/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - mysql-exporter

  mysql-exporter:
    image: prom/mysqld-exporter:v0.15.1
    container_name: mysql-exporter
    volumes:
      - ./monitoring/promethues/mysql_exporter/.my.cnf:/cnf/.my.cnf
    command:
      - '--config.my-cnf=/cnf/.my.cnf'
    restart: unless-stopped
    depends_on:
      - mysql_db
    ports:
      - 9104:9104

  grafana_service:
    image: grafana/grafana:10.3.6
#    container_name: grafana_service
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
secrets:
   app_api_key:
    file: app_api_secret.txt