name: weatherwiz
services:

  nginx-frontend:
    build:  ./frontend/
    container_name: nginx-frontend
    restart: always
    networks:
      - weather-app
      - monitor-net
    ports:
      - 80:80
    depends_on:
      - flask-backend

  flask-backend:
    build: ./backend/
    container_name: flask-backend
    secrets:
      - app_api_key
    ports:
      - "5100:5100"
    networks:
      - weather-app
    depends_on:
      mysql-db:
        condition: service_healthy

  mysql-db:
    build: ./db/
    container_name: mysql-db
    restart: always
    networks:
      - weather-app
    ports:
      - "3306:3306"

  prometheus:
    image: prom/prometheus:v2.51.2
    container_name: prometheus
    ports:
      - "9091:9090"
    restart: always
    networks:
      - monitor-net
    volumes:
      - ./monitoring/promethues/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - mysql-exporter

  mysql-exporter:
    image: prom/mysqld-exporter:v0.15.1
    container_name: mysql-exporter
    volumes:
      - ./monitoring/promethues/mysql_exporter/.my.cnf:/cnf/.my.cnf
    command:
      - '--config.my-cnf=/cnf/.my.cnf'
    networks:
      - monitor-net
      - weather-app
    restart: unless-stopped
    depends_on:
      - mysql-db
    ports:
      - 9104:9104

  nginx-prometheus-exporter:
    image: nginx/nginx-prometheus-exporter:1.1.0
    container_name: nginx-prometheus-exporter
    ports:
      - 9113:9113
    networks: 
      - monitor-net
    command: --nginx.scrape-uri=http://frontend:80/status
    depends_on:
      - nginx-frontend

  grafana:
    image: grafana/grafana:11.0.0
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./monitoring/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    restart: unless-stopped
    networks:
      - monitor-net
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus
secrets:
   app_api_key:
    file: app_api_secret.txt

networks:
  weather-app:
    driver: bridge
  monitor-net:
    driver: bridge