services:

  front_end:
    build:  ./frontend/
    container_name: frontend
    restart: always
    ports:
      - 80:80
    depends_on:
      - flask_app

  flask_app:
    build: ./backend/
    container_name: flask_app
    secrets:
      - app_api_key
    ports:
      - "5100:5100"
    depends_on:
      mysql_db:
        condition: service_healthy

  mysql_db:
    build: ./db/
    container_name: mysql_db
    restart: always
    ports:
      - "3306:3306"
    expose:
      - "3306"

secrets:
   app_api_key:
    file: app_api_secret.txt