{
 "title": "WeatherWiz Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Frontend Nginx",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "NGINX Status",
     "type": "stat",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "nginx_up{job=\"nginx_exporter\"}"
      }
     ]
    },
    {
     "title": "Total requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(nginx_http_requests_total{}[5m])",
       "legendFormat": "{{instance}} total requests"
      }
     ]
    },
    {
     "title": "Processed connections",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(nginx_connections_accepted{}[5m])",
       "legendFormat": "{{instance}} accepted"
      },
      {
       "expr": "irate(nginx_connections_handled{}[5m])",
       "legendFormat": "{{instance}} handled"
      }
     ]
    },
    {
     "title": "Active Connections",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "nginx_connections_active{}", "legendFormat": "{{instance}} active" },
      { "expr": "nginx_connections_reading{}", "legendFormat": "{{instance}} reading" },
      {
       "expr": "nginx_connections_waiting{instance=~\"$instance\"}",
       "legendFormat": "{{instance}} waiting"
      },
      {
       "expr": "nginx_connections_writing{instance=~\"$instance\"}",
       "legendFormat": "{{instance}} writing"
      }
     ]
    }
   ]
  },
  {
   "title": "Database MySQL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "stat",
     "description": "**Uptime**\n\nThe amount of time since the last restart of the MySQL server process.",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      { "calculatedInterval": "10m", "expr": "mysql_global_status_uptime{}", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "Current QPS",
     "type": "stat",
     "description": "**Current QPS**\n\nBased on the queries reported by MySQL's ``SHOW STATUS`` command, it is the number of statements executed by the server within the last second. This variable includes statements executed within stored programs, unlike the Questions variable. It does not count \n``COM_PING`` or ``COM_STATISTICS`` commands.",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "rate(mysql_global_status_queries{}[$__interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "InnoDB Buffer Pool",
     "type": "stat",
     "description": "**InnoDB Buffer Pool Size**\n\nInnoDB maintains a storage area called the buffer pool for caching data and indexes in memory.  Knowing how the InnoDB buffer pool works, and taking advantage of it to keep frequently accessed data in memory, is one of the most important aspects of MySQL tuning. The goal is to keep the working set in memory. In most cases, this should be between 60%-90% of available memory on a dedicated database host, but depends on many factors.",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "mysql_global_variables_innodb_buffer_pool_size{}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "MySQL Questions",
     "type": "timeseries",
     "description": "**MySQL Questions**\n\nThe number of statements executed by the server. This includes only statements sent to the server by clients and not statements executed within stored programs, unlike the Queries used in the QPS calculation. \n\nThis variable does not count the following commands:\n* ``COM_PING``\n* ``COM_STATISTICS``\n* ``COM_STMT_PREPARE``\n* ``COM_STMT_CLOSE``\n* ``COM_STMT_RESET``",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_questions{}[$__interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "MySQL Connections",
     "type": "timeseries",
     "description": "**Max Connections** \n\nMax Connections is the maximum permitted number of simultaneous client connections. By default, this is 151. Increasing this value increases the number of file descriptors that mysqld requires. If the required number of descriptors are not available, the server reduces the value of Max Connections.\n\nmysqld actually permits Max Connections + 1 clients to connect. The extra connection is reserved for use by accounts that have the SUPER privilege, such as root.\n\nMax Used Connections is the maximum number of connections that have been in use simultaneously since the server started.\n\nConnections is the number of connection attempts (successful or not) to the MySQL server.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "sum(max_over_time(mysql_global_status_threads_connected{}[$__interval]))",
       "legendFormat": "Connections"
      },
      {
       "calculatedInterval": "2m",
       "expr": "sum(mysql_global_status_max_used_connections{})",
       "legendFormat": "Max Used Connections"
      },
      {
       "calculatedInterval": "2m",
       "expr": "sum(mysql_global_variables_max_connections{job=~\"$job\", instance=~\"$instance\"})",
       "legendFormat": "Max Connections"
      }
     ]
    },
    {
     "title": "MySQL Network Traffic",
     "type": "timeseries",
     "description": "**MySQL Network Traffic**\n\nHere we can see how much network traffic is generated by MySQL. Outbound is network traffic sent from MySQL and Inbound is network traffic MySQL has received.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "sum(rate(mysql_global_status_bytes_received{}[$__interval]))",
       "legendFormat": "Inbound"
      },
      {
       "calculatedInterval": "2m",
       "expr": "sum(rate(mysql_global_status_bytes_sent{}[$__interval]))",
       "legendFormat": "Outbound"
      }
     ]
    }
   ]
  },
  {
   "title": "Backend FLASK",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total requests per minute home",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 19, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(request_counter_total{instance=\"nginx-frontend:80\",job=\"flask-backend\",endpoint=\"/\",http_status=\"200\",method=\"GET\"}[1m])",
       "legendFormat": "HTTP {{ status }}"
      }
     ]
    },
    {
     "title": "Memory usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 5, "x": 19, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{job=\"flask-backend\"}",
       "legendFormat": "mem - {{instance}}"
      }
     ]
    },
    {
     "title": "Total requests per minute metrics",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 19, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(request_counter_total{instance=\"nginx-frontend:80\",job=\"flask-backend\",endpoint=\"/metrics\",http_status=\"200\",method=\"GET\"}[1m])",
       "legendFormat": "HTTP {{ status }}"
      }
     ]
    },
    {
     "title": "CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 5, "x": 19, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{job=\"flask-backend\"}[30s])",
       "legendFormat": "cpu"
      }
     ]
    },
    {
     "title": "Requests per second",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(request_counter_total{instance=\"nginx-frontend:80\",job=\"flask-backend\",http_status=\"200\"}[1m])",
       "legendFormat": "{{ path }}"
      }
     ]
    },
    {
     "title": "Errors per second",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 9, "x": 10, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(request_counter_total{instance=\"nginx-frontend:80\",job=\"flask-backend\",http_status!=\"200\"}[1m])",
       "legendFormat": "errors"
      }
     ]
    },
    {
     "title": "process open fds",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 5, "x": 19, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "process_open_fds{job=\"flask-backend\"}",
       "legendFormat": "cpu"
      }
     ]
    }
   ]
  }
 ]
}