swagger: "2.0"
info:
  version: "1.0.0"
  title: "Weather wiz API documentation"
basePath: "/api"

paths:
  /users:
    get:
      summary: "Get all users"
      responses:
        200:
          description: "Successful response"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/User"
    post:
      summary: "Create a new user"
      parameters:
        - name: "user"
          in: "body"
          description: "User object"
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        201:
          description: "User created"
          schema:
            $ref: "#/definitions/User"

definitions:
  User:
    type: "object"
    properties:
      id:
        type: "integer"
      name:
        type: "string"