FROM grafana/grafana:11.0.0
WORKDIR /etc/grafana/provisioning/dashboards
COPY provisioning/dashboards /etc/grafana/provisioning/dashboards
WORKDIR /etc/grafana/provisioning/datasources
COPY provisioning/datasources /etc/grafana/provisioning/datasources
