global:
  scrape_interval: 15s
  evaluation_interval:  15s

scrape_configs:

  - job_name: 'flask-backend'
    scrape_interval: 30s
    static_configs:
      - targets: ['nginx-frontend:80']

  - job_name: mysql_exporter
    static_configs:
      - targets: ['mysql-exporter:9104']

  - job_name: nginx_exporter
    static_configs:
      - targets: ['nginx-prometheus-exporter:9113']

  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100']
