global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'flask-backend'
    static_configs:
      - targets: ['flask-backend:5100']

  - job_name: mysql_exporter
    static_configs:
      - targets: ['mysql-exporter:9104']

  - job_name: nginx_exporter
    static_configs:
      - targets: ['nginx-prometheus-exporter:9113']