global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'flask_app'
    static_configs:
      - targets: ['flask_app:5100']

  - job_name: mysql_exporter
    static_configs:
      - targets: ['mysql-exporter:9104']