name: CI workflow

on:
  push:
    branches:
      - ci_flow
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Write secret to file
        run: echo "${{ secrets.WEATHER_APP_API_TOKEN }}" > app_api_secret.txt
        shell: bash    

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      - name: Set up Docker Compose
        run: |
          pwd
          docker compose up -d 

      - name: Tests
        run: |
          # Add your test commands here
          curl -f http://localhost:80 || exit 1 
          
# - name: Login to DockerHub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Build and push
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: .
      #     push: true
      #     tags: ${{ secrets.DOCKER_USERNAME }}/your-app:latest          