name: CI/CD Pipeline

on:
  push:
    branches: [ merge_pre_branch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: merge_pre_branch